### ISSUE TITLE
batchSize meaning

### ISSUE THREAD

**Issue by EricDosReis** [timdp/winston-aws-cloudwatch#104]
The default value of `batchSize` is 20, does this mean the maximum number of log events per submission is 20?

**Comment by EricDosReis** [comment]
No feedback, I will close.

**Comment by timdp** [comment]
Sorry about the late response. `batchSize` is indeed the number of log events included in a single CloudWatch request. The theoretical maximum is 10,000, but [there are multiple limitations](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/CloudWatchLogs.html#putLogEvents-property) so you may need to tweak the settings to your use case.

**Comment by EricDosReis** [comment]
Thank you so much @timdp for the explanation.
