### ISSUE TITLE
Role based Authentication

### ISSUE THREAD

**Issue by SanthoshKumar-Prodapt** [timdp/winston-aws-cloudwatch#107]
Right now the package allows us to authenticate using IAM User 

```
awsConfig: {
        accessKeyId: '...',
        secretAccessKey: '...',
        region: '...'
      },
```

As per the AWS Documentation, authentication can be done via IAM Role, is it possible to enable the feature?
https://github.com/awsdocs/amazon-cloudwatch-user-guide/blob/master/doc_source/auth-and-access-control-cw.md#authentication-cw

by which, instead of using IAM User, we can use IAM Role.

**Comment by timdp** [comment]
Like most other settings, `awsConfig` is optional. If you leave it out, it'll just delegate to the AWS SDK, which will inherit from the environment. That's how, among other things, IAM roles are supported.
