### ISSUE TITLE
Add transport to new winston.Logger() instance

### ISSUE THREAD

**Issue by mrhaynesy** [timdp/winston-aws-cloudwatch#3]
Hi I am trying to add cloudwatch to an instance of winston logger by passing it in:

var logger = new winston.Logger({
    transports: [
        new cloudWatchTransport({
            logGroupName: 'demo-group-1',
            logStreamName: 'demo-stream-1',
            createLogGroup: true,
            createLogStream: true,
        }),
    ],
    exitOnError: false
});

Does not seem to work, I am able to get it working using your example but it looks as if I don't understand the difference in transports config.

Does winston-aws-cloudwatch support this?

**Comment by timdp** [comment]
You're basically using it the way I do, so there's no reason why it wouldn't work. :smile:

The module uses `debug`, so you can run it with the environment variable `DEBUG=winston-aws-cloudwatch:*` applied. Does that show anything useful?

Also, if an error occurs, you should get an `error` event as documented in the readme. ~~If you don't, Node will actually crash.~~ Did you do that?

**Edit:** I missed the `exitOnError` in your code.

**Comment by mrhaynesy** [comment]
Ah silly me I was testing using logging in our tests running under mocha.
Since we don't have many tests yet mocha seems to finish and kill the process.

I made a test file to call logger directly and wait for response, all works fine. 
Thanks for response and the package!

**Comment by timdp** [comment]
All logging happens asynchronously, so killing the process is going to be a problem. Does mocha call process.exit() though? I've never encountered that.

However, you should exercise caution when you call a winston log function. There's currently no elegant way to ensure that all logging has completed. What I usually do is build a logger facade that passes a callback to every log call, which gets executed after all transports are done logging that one message. Then it's a matter of keeping a counter of pending logs in the facade and making sure that you wait until the counter gets to 0.

Glad to be of assistance!
