### ISSUE TITLE
When we receive an error from CloudWatch this library calls `unhandled exceptions`

### ISSUE THREAD

**Issue by danilvalov** [timdp/winston-aws-cloudwatch#32]
[winston-cloudwatch](https://github.com/lazywithclass/winston-cloudwatch) library has an option `errorHandler`. And when we receive errors from CloudWatch we can handle it.

Your library calls unhandled exceptions when we receive errors from CloudWatch. And options `logger.emitErrs = false;` and `logger.on('error', function (err) { /* Do Something */ });` from [winston](https://github.com/winstonjs/winston#events-and-callbacks-in-winston) don't work for me.

I need to listen unhandled exceptions when we receive an error from CloudWatch. And now I can do it to add try/catch javascript handler but it's very bad practice.

How to handle errors from CloudWatch?

**Comment by timdp** [comment]
Are you sure you're attaching the error listeners to the right object? As I understand it:
1. A winston logger is an EventEmitter, so you can use `logger.on('error', fn)` like you mentioned.
2. A transport is also an EventEmitter, so you also listen for individual transport errors by using `transport.on('error', fn)`.
3. If a transport emits an error and there is no listener, it will bubble up to the logger.
4. If an error bubbles up from a transport, or if the logger itself encounters an error, and there is no error listener, Node will emit an `uncaughtException` event and crash unless you have a listener that handles it.

In my own code, I generally attach an error listener to both the transport and the logger, which makes it easier to distinguish between the two. I haven't run into any uncaught errors but I won't rule out that CloudWatch just hasn't failed yet--although that's unlikely.

**Comment by danilvalov** [comment]
@timdp 
Thanks! `transport.on('error', fn)` works for me.
