### ISSUE TITLE
Logging in JSON format.

### ISSUE THREAD

**Issue by aayushijain23** [timdp/winston-aws-cloudwatch#49]
Hi,

Is there a way of logging the logs in the JSON format using winston-aws-cloudwatch. In winston-cloudwatch, there is an option of setting the jsonMessage: true, which gets the logs in json format. Using your library, I tried using formatLogs, but it doesn't help either.

Thanks,
Aayushi Jain.

**Comment by timdp** [comment]
Did you try something like

```js
formatLog: function (item) {
  return JSON.stringify(item)
}
```

I haven't used that feature of winston-cloudwatch myself, so I'd need to look into what it does exactly ...

CloudWatch Logs themselves are just strings though. It's just the Web front end that parses out JSON on the client side.

**Comment by aayushijain23** [comment]
Well, this is exactly what I tried as a last option but with a slight change. Using 
`formatLog: function (item) {
  return JSON.stringify(item.meta)
}`
This gives me the metadata as a json object. When using winston-cloudwatch, winston itself adds the level and the message as a part of the object. I also wanted the level and message as a part of the object, which I'm able to achieve by stringifying just the item as you suggested. Thanks.
