### ISSUE TITLE
Typescript throws Error: Cannot find module './lib/'

### ISSUE THREAD

**Issue by naishe** [timdp/winston-aws-cloudwatch#86]
When tried with Typescript, winston-aws-cloudwatch throws the following error when I try to run the project by running `npm run watch`. You get the same result if you compile and run `node dist/index.js`:

```
[TypeScript] 20:46:50 - Found 0 errors. Watching for file changes.
[Node] [nodemon] restarting due to changes...
[Node] [nodemon] starting `node dist/index.js`
[Node] [nodemon] restarting due to changes...
[Node] [nodemon] starting `node dist/index.js`
[Node] module.js:538
[Node]     throw err;
[Node]     ^
[Node]
[Node] Error: Cannot find module './lib/'
[Node]     at Function.Module._resolveFilename (module.js:536:15)
[Node]     at Function.Module._load (module.js:466:25)
[Node]     at Module.require (module.js:579:17)
[Node]     at require (internal/module.js:11:18)
[Node]     at Object.<anonymous> (/Users/nishant/dev/winston-aws/dist/node_modules/winston-aws-cloudwatch/index.js:1:80)
[Node]     at Module._compile (module.js:635:30)
[Node]     at Object.Module._extensions..js (module.js:646:10)
[Node]     at Module.load (module.js:554:32)
[Node]     at tryModuleLoad (module.js:497:12)
[Node]     at Function.Module._load (module.js:489:3)
```

I have setup a minimal Short Self Contained Compilable Example here: https://github.com/naishe/sscce-winston-aws-cloudwatch-ts

Am I missing something?

Thanks.

**Comment by naishe** [comment]
Here is some more information.

```
$ ls node_modules/winston-aws-cloudwatch
LICENSE      README.md    index.js     lib          package.json
$ ls dist/node_modules/winston-aws-cloudwatch
index.js     index.js.map
```

I see the `lib` dir is not copied over to build directory. I am still not able to figure out how to fix it.

**Comment by timdp** [comment]
I'm no TypeScript expert so I can't help you there. Since the `lib` folder is under `node_modules`, it's definitely not an error at the package level. I guess the TypeScript compiler needs to be instructed to copy the package over? It should be able to figure that out by looking at `index.js` though.

**Comment by naishe** [comment]
Yes, you are right. It does. It is my `tsconfig` that was causing the issue. I wrote a longish explanation on [Stackoverflow](https://stackoverflow.com/questions/50923585/typescript-cannot-find-module-lib/50931553#50931553).

Thanks, closing this.
